# Generated by Django 5.0.6 on 2024-06-13 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade_api', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='posts',
            field=models.ManyToManyField(related_name='posts', through='arcade_api.Post', to=settings.AUTH_USER_MODEL),
        ),
    ]
