# Generated by Django 5.0.6 on 2024-07-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade_api', '0003_clan_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
