# Generated by Django 5.0.6 on 2024-10-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade_api', '0006_game_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game',
            field=models.CharField(max_length=40),
        ),
    ]
