# Generated by Django 5.0.6 on 2024-10-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade_api', '0008_alter_game_player'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trophier',
            constraint=models.UniqueConstraint(fields=('gamer', 'trofeo'), name='unique_gamer_trofeo'),
        ),
    ]
